[build]
  command = "cd web-app && npm install --legacy-peer-deps && npm run build"
  publish = "web-app/build/client"

[env]
  DATABASE_URL = "postgresql://neondb_owner:npg_NWeKU1gJI3GF@ep-patient-king-aby4il44-pooler.eu-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
